export const SET_NAME = "SET_NAME";
export const SET_SERVER = "SET_SERVER";
export const SET_ROLE = "SET_ROLE";

export const RESET_QUESTION = "RESET_QUESTION";
export const SET_QUESTION = "SET_QUESTION";

export const SET_QUESTION_INFO = "SET_QUESTION_INFO";
export const SET_QUESTION_TYPE = "SET_QUESTION_TYPE";
export const SET_QUESTION_TIME = "SET_QUESTION_TIME";
export const SET_QUESTION_SCORE = "SET_QUESTION_SCORE";

export const SET_MULTIPLECHOICE = "SET_MULTIPLECHOICE";
export const SET_MULTIPLECHOICE_ANSWER = "SET_MULTIPLCHOICE_ANSWER";
export const SET_MULTIPLECHOICE_ANSWER_TEXT = "SET_MULTIPLECHOICE_ANSWER_TEXT";
export const SET_MULTIPLECHOICE_ANSWER_CORRECT =
	"SET_MULTIPLE_CHOICE_ANSWER_CORRECT";
export const SET_MULTIPLECHOICE_QUESTION = "SET_MULTIPLECHOICE_QUESTION";

export const SET_MATCHING = "SET_MATCHING";
export const SET_MATCHING_VALUE = "SET_MATCHING_VALUE";
export const SET_MATCHING_PROPERTY = "SET_MATCHING_PROPERTY";

export const SET_MATCHING_ANSWERS = "SET_MATCHING_ANSWERS";

export const SET_QUESTION_SUBMITTED = "SET_QUESTION_SUBMITTED";

export const SET_TIME_LEFT = "UPDATE_TIME_LEFT";

export const SET_SCORE = "SET_SCORE";
