export const ADD_NAME = "ADD_NAME";
export const ADD_SERVER = "ADD_SERVER";
export const ADD_ROLE = "ADD_ROLE";
export const ADD_MULTIPLECHOICE_ANSWER = "ADD_MULTIPLECHOICE_ANSWER";
export const ADD_MULTIPLECHOICE_QUESTION = "ADD_MULTIPLECHOICE_QUESTION";
export const ADD_MATCHING_VALUE = "ADD_MATCHING_VALUE";
export const ADD_MATCHING_PROPERTY = "ADD_MATCHING_PROPERTY";
